//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voter.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Voter.Web.Resources.Dictionary", typeof(Dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatný formulář.
        /// </summary>
        public static string Global_AntiForgery {
            get {
                return ResourceManager.GetString("Global_AntiForgery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voter.
        /// </summary>
        public static string Global_ApplicationName {
            get {
                return ResourceManager.GetString("Global_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivovat.
        /// </summary>
        public static string Global_Button_Activate {
            get {
                return ResourceManager.GetString("Global_Button_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat.
        /// </summary>
        public static string Global_Button_Add {
            get {
                return ResourceManager.GetString("Global_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět.
        /// </summary>
        public static string Global_Button_Back {
            get {
                return ResourceManager.GetString("Global_Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět domů.
        /// </summary>
        public static string Global_Button_BackToHome {
            get {
                return ResourceManager.GetString("Global_Button_BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpátky na stránku.
        /// </summary>
        public static string Global_Button_BackToPage {
            get {
                return ResourceManager.GetString("Global_Button_BackToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybrat.
        /// </summary>
        public static string Global_Button_Choose {
            get {
                return ResourceManager.GetString("Global_Button_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit kopii.
        /// </summary>
        public static string Global_Button_Clone {
            get {
                return ResourceManager.GetString("Global_Button_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit.
        /// </summary>
        public static string Global_Button_Create {
            get {
                return ResourceManager.GetString("Global_Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivovat.
        /// </summary>
        public static string Global_Button_Deactivate {
            get {
                return ResourceManager.GetString("Global_Button_Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výchozí.
        /// </summary>
        public static string Global_Button_Default {
            get {
                return ResourceManager.GetString("Global_Button_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        public static string Global_Button_Delete {
            get {
                return ResourceManager.GetString("Global_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Global_Button_Detail {
            get {
                return ResourceManager.GetString("Global_Button_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit.
        /// </summary>
        public static string Global_Button_Edit {
            get {
                return ResourceManager.GetString("Global_Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokončit.
        /// </summary>
        public static string Global_Button_Finish {
            get {
                return ResourceManager.GetString("Global_Button_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obnovit.
        /// </summary>
        public static string Global_Button_Restore {
            get {
                return ResourceManager.GetString("Global_Button_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string Global_Button_Save {
            get {
                return ResourceManager.GetString("Global_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storno.
        /// </summary>
        public static string Global_Button_Storno {
            get {
                return ResourceManager.GetString("Global_Button_Storno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload fota.
        /// </summary>
        public static string Global_Button_UploadPhoto {
            get {
                return ResourceManager.GetString("Global_Button_UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položka byla úspěšně přidána.
        /// </summary>
        public static string Global_Create_SuccessNotification {
            get {
                return ResourceManager.GetString("Global_Create_SuccessNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položka byla úspěšně smazána.
        /// </summary>
        public static string Global_Delete_SuccessNotification {
            get {
                return ResourceManager.GetString("Global_Delete_SuccessNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položka byla úspěšně upravena.
        /// </summary>
        public static string Global_Edit_SuccessNotification {
            get {
                return ResourceManager.GetString("Global_Edit_SuccessNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampaně.
        /// </summary>
        public static string Vote_Campaigns_Title {
            get {
                return ResourceManager.GetString("Vote_Campaigns_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otázky.
        /// </summary>
        public static string Vote_Questions_Title {
            get {
                return ResourceManager.GetString("Vote_Questions_Title", resourceCulture);
            }
        }
    }
}
